apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
spec:
 config: |
   {
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "ens1f0",
      "mode": "bridge",
      "ipam": {
          "type": "static",
            "addresses": [
             {
               "address": "192.168.11.3/24"
             }
            ],
            "routes": [
               { "dst": "0.0.0.0/0", "gw": "192.168.11.254" }
         ]
      }
   }
