apiVersion: v1
kind: Pod
metadata:
  name: sriov-app-1
  labels:
    app: nginx
  namespace: sriov-app
  annotations:
    k8s.v1.cni.cncf.io/networks: sriovnetwork
spec:
 securityContext:
   allowPrivilegeEscalation: true
   privileged: true
 containers:
   - name: sriov-app-1
     image: 'registry.necdtvran.localdomain:5000/nec-nfvi/nfvi-ocp/4.12/centos/tools:latest'
     ports:
       - containerPort: 8080
         protocol: TCP
     command:
     - /sbin/init
     resources:
       limits:
         cpu: "8"
         openshift.io/netdevice: "1"
     requests:
         cpu: "8"
         openshift.io/netdevice: "1"
